version: '3.4'

services:
  keda.samples.worker.servicebus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - KEDA_SERVICEBUS_QUEUE_NAME=orders
     
      # Authentication mode: Connection string
      - KEDA_SERVICEBUS_AUTH_MODE=ConnectionString
      - KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING=<connection-string>
      
      # Authentication mode: Service Principle
      # - KEDA_SERVICEBUS_AUTH_MODE=ServicePrinciple
      # - KEDA_SERVICEBUS_HOST_NAME=<service-bus-namespace>.servicebus.windows.net
      # - KEDA_SERVICEBUS_TENANT_ID=<ad-tenant-id>
      # - KEDA_SERVICEBUS_IDENTITY_APPID=<ad-idenity-app-id>
      # - KEDA_SERVICEBUS_IDENTITY_SECRET=<ad-idenity-app-secret>
      
      # Authentication mode: Managed Identity
      #- KEDA_SERVICEBUS_AUTH_MODE=ManagedIdentity
      #- KEDA_SERVICEBUS_HOST_NAME=<service-bus-namespace>.servicebus.windows.net
      #  Optionally specify ID of user-assigned application identity
      #- KEDA_SERVICEBUS_IDENTITY_USERASSIGNEDID=<ad-idenity-app-id>
  keda.samples.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING=<connection-string>